# Generated by Django 5.1.3 on 2024-11-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, unique=True)),
                ("author", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
            ],
        ),
    ]
